"""Event constants for workflow orchestration logs."""

WORKFLOW_CREATED = "WORKFLOW_CREATED"
WORKFLOW_UPDATED = "WORKFLOW_UPDATED"
WORKFLOW_EXECUTION_STARTED = "WORKFLOW_EXECUTION_STARTED"
WORKFLOW_NODE_STARTED = "WORKFLOW_NODE_STARTED"
WORKFLOW_NODE_COMPLETED = "WORKFLOW_NODE_COMPLETED"
WORKFLOW_NODE_FAILED = "WORKFLOW_NODE_FAILED"
WORKFLOW_FINISHED = "WORKFLOW_FINISHED"
